server:
    port: 6969
spring: 
  datasource:
    password: 
    url: jdbc:h2:mem:jumma_password_manager_db
    username: jumma_ahmed
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

